### PR TITLE
[resolves #32] Comprehensive setup/run instructions for Cardano Docker

### LINKED ISSUE #32: Comprehensive docs Cardano Docker

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by rdlrt** [comment]
Umm I am not sure if this is a good place for docker. Again, the user base knowledge on what / how to configure security when using docker is quite subjective.

More importantly, the stake pool school documentation is to make aspiring pool operators to actually learn the commands and get familiar with setup of a pool and CLI usage. Using ready made scripts (or even worse a ready docker image that can be modified by someone) is quite counter productive. There is a reason why other scripts/tools are not included in the school.

**Comment by adrem1** [comment]
@rdlrt I agree fully. Further, many SPOs like the 'purist' approach of doing everything within the boundaries of the software as intended. Also, docker images have partially been responsible for catastrophic losses by other SPOs, as reported on the forum. Just my 2 cents.

**Comment by tdiesler** [comment]
The future of runtime will be containerized. At least that is the firm believe of companies associated in with the [Open Container Initiative](https://opencontainers.org/) - you may recognize some those members. Here at RedHat for example we have seen quite a dramatic increase in containerized payloads over the last couple of years. I would even go as far as to say, it is in reality quite the contrary to what you describe above. Professional operators for critical systems seem to much prefer the reliability, security, management/orchestration capabilities of well designed containers. The scope of error is in fact much reduced with the containerized approach - and this by order of magnitude.

Perhaps its not the right time for Cardano just yet, which is of course quite ok. 

To do this properly, a well designed image that officially comes from IOHK would be needed. An improved version of [inputoutput/cardano-node](https://hub.docker.com/r/inputoutput/cardano-node) is probably what you're looking for. The image should support multiple architectures, have graceful shutdown, be configurable according the standards such that it runs well in managed environments (i.e. Kubernetes), have readyness/liveness probes, have this or that other support functionality built-in and of course be well documented.

It is also worth thinking about a scope beyond that of stake pool operators. How would large companies incorporate Cardano nodes as part of their IT infrastructure? It is well possible that (in the future) large organizations have data streams targeted or sources from Cardano. These organizations would be looking for an appropriate container to deploy in their container environments.

Anyway, it was perhaps a little clumsy from my part to start a conversation about a proper Cardano image through a docs pull request - I'm sorry about that. I'd be very grateful, if you could help me to reach the right people to discuss this a little further.

cheers
-- thomas

**Comment by rdlrt** [comment]
>  its not the right time for Cardano just yet

Its not about whether its relevant to cardano or not. Keeping the rest aside, the intent of Cardano Stake Pool School documentation is to educate SPOs to be able to familiarise with the system and node operations.

Enhancements to those images would be very much welcome, but perhaps [cardano-node](https://github.com/input-output-hk/cardano-node) and/or [iohk-ops](https://github.com/input-output-hk/iohk-ops) are better places where you could add your contributions further.

**Comment by tdiesler** [comment]
Ok thanks. I'll do that and if all goes well we can worry about where and how the result can be document

**Comment by adrem1** [comment]
@tdiesler apologies if my previous comment came off a bit short. I was and am thinking solely from a budding SPO perspective.

All the best for your future endeavours!

Cheers,

A

**Pull request closed without merging**
